### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by pdrgrl** [farique1/diffusion-browser#1]
Hello, 

How would I got about using diffusion browser?

Thank you!

**Comment by farique1** [comment]
Hi.
If you are using SD locally I will assume you have the latest Python installed, if not you have to install it first.
Then you have to install the PIL module (here: https://pillow.readthedocs.io/en/stable/) to deal with the images.
After that download the Diffusion Browser repository zip and unzip it where you want it to be. Open a terminal window on the Diffusion Browser folder and type:
python difbrow.py
(If you already have Python 2 installed, in a Mac, for instance, type python3)
Once Diffusion Browser is running click the path button and point to the top folder where your images are.
That is it.
These instructions are for Windows, I haven't tested it with Mac or Linux but I don't think there should be any problem. The instructions are also similar in any system.
If you find any problem let me know.

**Comment by pdrgrl** [comment]
Thank you! 

I was able to install it and run it

**Comment by farique1** [comment]
Nice!
Cheers.

**Comment by farique1** [comment]
Nic
