### ISSUE TITLE
Error with Auto1111 generated images

### ISSUE THREAD

**Issue by RandomLegend** [farique1/diffusion-browser#2]
Hello,

so i just installed this image browser and want to use it with the newest Auto1111 images.

However i get this error: 

`Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/frank-garuda/Programme/STABLE-DIFFUSION/Tools/diffusion-browser/difbrow.py", line 940, in <lambda>
    buttons[i][j]['command'] = lambda arg=image_path[i][j], btn=buttons[i][j]: _on_click(arg, btn)
  File "/home/frank-garuda/Programme/STABLE-DIFFUSION/Tools/diffusion-browser/difbrow.py", line 221, in _on_click
    embed_par.sort(key=lambda i: TEXT_TAGS.index(i[0]))
  File "/home/frank-garuda/Programme/STABLE-DIFFUSION/Tools/diffusion-browser/difbrow.py", line 221, in <lambda>
    embed_par.sort(key=lambda i: TEXT_TAGS.index(i[0]))
ValueError: 'negative prompt' is not in list`

**Comment by farique1** [comment]
Hi,
I can't dig deeper at the moment, but I think they added new tags to the embedded information.
You can add "negative prompt" as shown in the ValueError to this list on the code:

TEXT_TAGS = ['embedded info',
             'prompt',
             'seed',
             'sampler',
             'sampler_name',
             'steps',
             'ddim_steps',
             'ddim_eta',
             ...

Add this and any other new tag that may cause an error. I'll try to test later to confirm that.

Cheers.

**Comment by farique1** [comment]
Hi,
I just fixed the Negative Prompt error.
Also added support for JPEG metadata.
Thanks for reporting the error.

**Comment by RandomLegend** [comment]
@farique1 
Sorry to bother, now it's the same error but with a different value:
![image](https://user-images.githubusercontent.com/38812603/205121378-cd966836-4aba-498a-964b-73b9578c7c70.png)

With generated images where you modified the CLIP_SKIP value

**Comment by farique1** [comment]
Hi,
No bother, your first report was very important.
The thing is I don't know all the tags Automatic1111 uses on the metadata
and the sort routine freaks out when a new one appears.
The way I found to solve it was making it easier to add new tags. Try
adding it to the text tags on the code (you can use notepad or any text
editor), here:

TEXT_TAGS = ['embedded info',
             'prompt',
             'negative prompt',
             'seed',
             'sampler',
             'sampler_name',
             'steps',
             'ddim_steps',
             'ddim_eta',
...
It would not have solved the "Negative prompt" problem but should work with
generic tags.
Let me know if it works.

Cheers.

* Fred Rique*
*Visite o site <http://sites.google.com/view/fred-rique>*

**Comment by RandomLegend** [comment]
Yeah i already added it there and it's fixed. So you can push that to your repo and it works.

Afaik i use quite possible every single option in the Auto1111 webui that could create additional paramters in the metadata.

So with those two added you should be good to go.

**Comment by farique1** [comment]
Cool!
I was about to ask you to send any other parameters you found (I couldn't
find a list of them anywhere).

Thanks.

* Fred Rique*
*Visite o site <http://sites.google.com/view/fred-rique>*

**Comment by farique1** [comment]
Hi,
Now it's me who is bothering, but since you seem to like and use Diffusion
Browser how about a sneak peek on the new version before I post it online?
I'm not using you as a beta tester but I'm using you as a beta tester :p
Just kidding, it's just a thank you, these upgrades only happened because
of your report :)

Cheers.

* Fred Rique*
*Visite o site <http://sites.google.com/view/fred-rique>*

**Comment by RandomLegend** [comment]
You aren't bothering me at all don't worry!
I'd love to have a sneak peak. However i was never really able to use the program, but i am quite sure that's on me...i am on linux and i use KDE Plasma as my DE. And whenever i start the program it gets stuck in a very small window size. Just enough so you can see a few images, altough very small. And when i clicked on those it generated the errors i posted here.

I am sure this is some jankyness on my system; Using some hacky wacky tiling window manager...

So i don't know if i am the right person here^^ I will try to get this stuff fixed but it's hard...it doesn't give me any error at all and i can make it smaller and resize it again back to it's original size, but that original size is too small to do anything...

[2022-12-02_15-56-33.webm](https://user-images.githubusercontent.com/38812603/205321927-d0168c41-6146-4996-970f-24bb8c906c58.webm)

**Comment by RandomLegend** [comment]
I don't want to edit because i gets confusing to see different things in the mail and here so i clarify

I started the comment with "i was never really able to use it" and took the video afterwards. But in the video i saw that it starts big enough to be usable. i don't know why it did that...so yeah i CAN use the program, i'm just not allowed to resize it lol.

So yeah, you can use me as a beta tester :-D

**Comment by farique1** [comment]
Nice! But I was really kidding about the beta testing :)
Anyway, there goes probably the last version before I publish it.
Enjoy.

* Fred Rique*
*Visite o site <http://sites.google.com/view/fred-rique>*

**Comment by RandomLegend** [comment]
You don't have to be kidding :-) I want to help

Where would i download this last version? oO

**Comment by farique1** [comment]
Sent by email, I'll attach here.
[difbrowSearch.zip](https://github.com/farique1/diffusion-browser/files/10166754/difbrowSearch.zip)

**Comment by RandomLegend** [comment]
interesting, didn't show up anywhere...well, i'll keep you updated!

Any other way to chat with you besides in this closed issue? :-D

**Comment by farique1** [comment]
Weird.
Do you have WhatsApp or Telegram?
