### ISSUE TITLE
Does this work on Windows?

### ISSUE THREAD

**Issue by mattehicks** [farique1/diffusion-browser#3]
Sorry - didnt know where to ask :)

**Comment by farique1** [comment]
No problem, it sure does, it was Made In Windows.
What problem are you having?

**Comment by Tobe2d** [comment]
+1 I cant find out how to run it on windows ;-)
I just see .sh

Any tips?

**Comment by farique1** [comment]
Sure, just open a terminal or command prompt on the Diffusion Browser folder and type "python difbrow.py".
Let me know if it worked.

**Comment by Tobe2d** [comment]
Thanks for the reply @farique1 
When I run python difbrow.py and select the output folder of automatic1111 it took sometime and all I see is this:

![image](https://user-images.githubusercontent.com/4099839/230125902-8ee492e9-b010-4d3b-af12-8a6e3cdaecca.png)


Edit:
adding the log:

```

E:\>cd diffusion-browser

E:\diffusion-browser>python difbrow.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "E:\Ai__Project\diffusion-browser\difbrow.py", line 346, in new_path
    reset_interface()
  File "E:\diffusion-browser\difbrow.py", line 902, in reset_interface
    main()
  File "E:\diffusion-browser\difbrow.py", line 1838, in main
    pop_menu = tk.Menu(root, tearoff=0, relief='flat', bg=FONT_COLOR,
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 3316, in __init__
    Widget.__init__(self, master, 'menu', cnf, kw)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 2601, in __init__
    self.tk.call(
_tkinter.TclError: No more menus can be allocated.
```

**Comment by farique1** [comment]
Weird. I'll take a look at that, unfortunately not until next week.
But just to rule that out, have you installed the Pillow library?

**Comment by Tobe2d** [comment]
I try installing Pillow again and it seems it is installed:

pip install Pillow

Requirement already satisfied: Pillow in c:\users\xxx\appdata\local\programs\python\python310\lib\site-packages (9.3.0)


Now when I try running the app again agot it to start loading the images and stuck on 754 of 3059 as you see below:
![image](https://user-images.githubusercontent.com/4099839/230139674-0b71859b-2294-4d5e-9cc2-d9fa785f3ddf.png)


is there limit for how many image in the folder and sub-folders?

**Comment by farique1** [comment]
Not that I know, I have tested it with more than 5k images without problems.
Does it show any errors,? Looks like a crash. Might be some corrupted or unreadable image file crashing the app. I put some safeguard to avoid damaged images but sure there must be cases I'm not covering.

**Comment by farique1** [comment]
Hi, @Tobe2d, did you managed to get it to work?
If not, I think I can send you a version showing the name of the image file currently loading so we can verify if it is a problem with one of them.

**Comment by Tobe2d** [comment]
@farique1 Yes please send me the file to check it out as it keep on freezing the same way

**Comment by farique1** [comment]
[difbrow.zip](https://github.com/farique1/diffusion-browser/files/11201356/difbrow.zip)
This version prints the currently loading file on the terminal. The last file show when it hangs should be the image it is not able to load.

**Comment by Tobe2d** [comment]
I replaced the file and run it and here is the log:


```
E:\stable-diffusion-webui\outputs\txt2img-images\syberart Create a tense and dramatic screenshot of\00001-3224348555.png
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 839, in callit
    func(*args)
  File "E:\diffusion-browser\difbrow.py", line 1866, in <lambda>
    root.after(50, lambda: first_run())
  File "E:\diffusion-browser\difbrow.py", line 1490, in first_run
    image_list = generate_image_list('', '', master=True)
  File "E:\diffusion-browser\difbrow.py", line 1139, in generate_image_list
    embed_text, embed_dict = read_image_info(original_image, file)
  File "E:\diffusion-browser\difbrow.py", line 1028, in read_image_info
    content = par_list[1].strip().lower()
IndexError: list index out of range
```
here is the image incase you want to have a look at the metadata or someghing:

![00001-3224348555](https://user-images.githubusercontent.com/4099839/231198972-49ba76be-0d79-4f91-9446-1e9cd8ba9271.png)

**Comment by farique1** [comment]
Ok, I think I know what happened.

The metadata format on these images is a mess, as far as I know there is no standard and not even a clear list of what parameters are described, so I have to guess the best as I can but it's going to fail some times.
In this particular case, I think the problem comes from the fact that "negative prompt" (along with a "\n" before it) do not comes after the positive prompt as usual and it is messing with the routine interpreting the metadata.
I'll try to better deal with these inconsistencies and catch and report potential errors instead of crashing the program.

Does it work after you remove this image from the folder? Do you have any other image with issues?

Thanks for reporting.

**Comment by Tobe2d** [comment]
Sounds correct as when I open the metadata it is mess.

Yes once I remove the image it continue counting until the next image with similar issue and stop again counting.

**Comment by farique1** [comment]
Looking ate this image metadata I cannot think of a way to correctly parse it.
[difbrow.zip](https://github.com/farique1/diffusion-browser/files/11202377/difbrow.zip)
For now, try this version. It should bypass the reading of the metadata if it gives an error, also it will print the offending file name to the terminal.

**Comment by Tobe2d** [comment]
It finish scaning this time giving this message:
![image](https://user-images.githubusercontent.com/4099839/231221335-1da50411-3c03-460a-8ea4-8dbf7c218c96.png)

I press yes and it opne as expected ;-)

**Comment by farique1** [comment]
Cool!
The way I "fixed" it is not the best but I will publish an updated version just so it crashes less.
Thanks again.
I'll close this issue but please report back if you have any other problem.
Cheers.

**Comment by Tobe2d** [comment]
Thank you @farique1
