### ISSUE TITLE
Exception in Tkinter callback

### ISSUE THREAD

**Issue by Tobe2d** [farique1/diffusion-browser#4]
Its me again ;-)

I try starting it again and now I have the below error:

```
E:\diffusion-browser>python difbrow.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "E:\diffusion-browser\difbrow.py", line 461, in <lambda>
    btn_accept['command'] = lambda conf_entries=conf_entries: accept_config(btn_accept, conf_entries)
  File "E:\diffusion-browser\difbrow.py", line 642, in accept_config
    reset_interface()
  File "E:\diffusion-browser\difbrow.py", line 902, in reset_interface
    main()
  File "E:\diffusion-browser\difbrow.py", line 1838, in main
    pop_menu = tk.Menu(root, tearoff=0, relief='flat', bg=FONT_COLOR,
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 3316, in __init__
    Widget.__init__(self, master, 'menu', cnf, kw)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 2601, in __init__
    self.tk.call(
_tkinter.TclError: No more menus can be allocated.
```

I havent changed anything from before. all I did closed it and after sometime I open again and got this above ;-(

**Comment by farique1** [comment]
Weird, the same issue you had before.
Took a quick look and could find nothing obvious.
I'll dig deeper, meanwhile:
Try downloading the updating repository (with the fixes I made earlier. also added a difbrow.bat).
And, please, tell me your version of tkinter.
   Call python from the terminal and:
      >>> import tkinter
      >>> tkinter.TkVersion

**Comment by Tobe2d** [comment]
>>> import tkinter
>>> tkinter.TkVersion
8.6

**Comment by farique1** [comment]
Same as mine.
Everywhere I look the cause is when menus are being generated multiple times.
I checked and DB is only creating one instance.
[difbrow.zip](https://github.com/farique1/diffusion-browser/files/11204166/difbrow.zip)
Can you try this version with the menu generation commented out?

**Comment by Tobe2d** [comment]
I've deleted the folder and cloned the repo again and it work!

I suspect it happen when it find a file and it index it somehow and get corrupted.

And I downloaded difbrow.zip and replaced and still working now.

I am not really sure what is happining here.

**Comment by farique1** [comment]
Me neither.
I suspected earlier something about a corrupted file but it doesn't make sense (the menu is created before loading the files and the saved information -parameters and .ini- is simple enough not to interfere with the menus).
What version of Windows are you using? Any addon that might be interfering with the graphical interface?
(Someone had a problem once by using a window manager on Linux)

**Comment by Tobe2d** [comment]
Yah I understand.

I am on windows 11 pro latest offical update. No add ons too

**Comment by farique1** [comment]
Normal environment.
Without being able to reproduce the problem and Google not helping, there is not much I can do.
If you figure out something more related to this problem, let me know.

**Comment by Tobe2d** [comment]
Sure. I will close it and reply here if I find out anything.

Thank you so much for all this ;-)
